addSbtPlugin("org.scalameta"      % "sbt-native-image"         % "0.3.2")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager"      % "1.8.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.11.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.10.1")
addSbtPlugin("io.spray"           % "sbt-revolver"             % "0.9.1")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"           % "1.5.7")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"              % "0.6.3")
